package com.cloudstaff.suiteview.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
@DynamoDBTable(tableName="ThreadSuiteView")
public class ThreadItem extends AbstractItem{

	private String threadkey;
	private String dateresolved;
	private String resolved;
	private String subject;
	private String timestamp;
	private String username;
	@DynamoDBHashKey(attributeName = "threadkey")
	@DynamoDBAutoGeneratedKey
	public String getThreadkey() {
		return threadkey;
	}
	public void setThreadkey(String threadkey) {
		this.threadkey = threadkey;
	}
	@DynamoDBAttribute(attributeName="dateresolved")
	public String getDateresolved() {
		return dateresolved;
	}
	public void setDateresolved(String dateresolved) {
		this.dateresolved = dateresolved;
	}
	@DynamoDBAttribute(attributeName="resolved")
	public String getResolved() {
		return resolved;
	}
	public void setResolved(String resolved) {
		this.resolved = resolved;
	}
	@DynamoDBAttribute(attributeName="subject")
	public String getSubject() {
		return subject;
	}
	public void setSubject(String subject) {
		this.subject = subject;
	}
	@DynamoDBAttribute(attributeName="timestamp")
	public String getTimestamp() {
		return timestamp;
	}
	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}
	@DynamoDBAttribute(attributeName="username")
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	
	
}
